language: perl
perl:
  - "5.30"
os:
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then 
      brew update;
      brew install berkeley-db;
      \curl -L https://install.perlbrew.pl bash;
      source ~/perl5/perlbrew/etc/bashrc;
    fi
