language: perl
perl:
  - "5.30"
  - "5.28"
  - "5.26"
os:
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then 
      brew update
      brew install berkeley-db
      \curl -L https://install.perlbrew.pl bash
      source ~/perl5/perlbrew/etc/bashrc
      perlbrew install https://www.cpan.org/src/5.0/perl-${TRAVIS_PERL_VERSION}.0.tar.gz
      perlbrew install-cpanm
    fi
