language: perl
perl:
  - "5.30"
  - "5.28"
  - "5.26"
os:
  - linux
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install libdb-dev; sudo apt-get -y install r-base; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew install berkeley-db; fi
