language: perl
perl:
  - "5.30"
  - "5.28"
  - "5.26"

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init --auto
  - sudo apt-get -y install libdb-dev
  - sudo apt-get -y install r-base
  - cpanm --notest Devel::Cover::Report::Coveralls

after_success:
  - cover -test -report coveralls
